services:
  bot:
    image: livechat-dl-bot:latest
    build:
      context: .
    container_name: livechat-dl-bot
    restart: unless-stopped
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      DOWNLOAD_DIR: /app/downloads
      UPLOAD_TO_DISCORD: ${UPLOAD_TO_DISCORD}
    volumes:
      - ./downloads:/app/downloads
    working_dir: /app/app
    command: ["python", "main.py"]