services:
  bot:
    image: livechat-dl-bot:latest
    build:
      context: .
    container_name: livechat-dl-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./cookies:/app/cookies

  bgutil-provider:
    image: brainicism/bgutil-ytdlp-pot-provider
    container_name: bgutil-ytdlp-pot-provider
    restart: unless-stopped
    init: true
